baseurl = "https://mdhalim.github.io"
title = "BlitzLiving"
copyright = "Copyright &copy; 2019 - MD Halim"
canonifyurls = true
theme = "kiera"
menu = "main"
meta ="categories"

paginate = 3

summaryLength = 30
enableEmoji = true
pygmentsCodeFences = true

[author]
    name = "Halim"
    github = "mdhalim"
    linkedin = "mdhalim"
    twitter = "haliminfinity"

[params]
    tagline = "Notes on tech, decentralization, philosophy and business"

